#ifndef INDEX_COMP_H
#define INDEX_COMP_H

#include <limits.h>

#include "config.h"
#include "pattern.h"
#include "const.h"


inline unsigned long int index_for_config_00(Config_store config) ;
inline unsigned long int index_for_config_01(Config_store config) ;
inline unsigned long int index_for_config_02(Config_store config) ;
inline unsigned long int index_for_config_03(Config_store config) ;
inline unsigned long int index_for_config_04(Config_store config) ;
inline unsigned long int index_for_config_05(Config_store config) ;
inline unsigned long int index_for_config_06(Config_store config) ;
inline unsigned long int index_for_config_07(Config_store config) ;
inline unsigned long int index_for_config_08(Config_store config) ;
inline unsigned long int index_for_config_09(Config_store config) ;
inline unsigned long int index_for_config_10(Config_store config) ;
inline unsigned long int index_for_config_11(Config_store config) ;
inline unsigned long int index_for_config_12(Config_store config) ;
inline unsigned long int index_for_config_13(Config_store config) ;
inline unsigned long int index_for_config_14(Config_store config) ;
inline unsigned long int index_for_config_15(Config_store config) ;
inline unsigned long int index_for_config_16(Config_store config) ;
inline unsigned long int index_for_config_17(Config_store config) ;
inline unsigned long int index_for_config_18(Config_store config) ;
inline unsigned long int index_for_config_19(Config_store config) ;
inline unsigned long int index_for_config_20(Config_store config) ;
inline unsigned long int index_for_config_21(Config_store config) ;
inline unsigned long int index_for_config_22(Config_store config) ;
inline unsigned long int index_for_config_23(Config_store config) ;
inline unsigned long int index_for_config_24(Config_store config) ;
inline unsigned long int index_for_config_25(Config_store config) ;
inline unsigned long int index_for_config_26(Config_store config) ;
inline unsigned long int index_for_config_27(Config_store config) ;
inline unsigned long int index_for_config_28(Config_store config) ;
inline unsigned long int index_for_config_29(Config_store config) ;
inline unsigned long int index_for_config_30(Config_store config) ;
inline unsigned long int index_for_config_31(Config_store config) ;
inline unsigned long int index_for_config_32(Config_store config) ;
inline unsigned long int index_for_config_33(Config_store config) ;
inline unsigned long int index_for_config_34(Config_store config) ;
inline unsigned long int index_for_config_35(Config_store config) ;
inline unsigned long int index_for_config_36(Config_store config) ;
inline unsigned long int index_for_config_37(Config_store config) ;
inline unsigned long int index_for_config_38(Config_store config) ;
inline unsigned long int index_for_config_39(Config_store config) ;
inline unsigned long int index_for_config_40(Config_store config) ;
inline unsigned long int index_for_config_41(Config_store config) ;
inline unsigned long int index_for_config_42(Config_store config) ;
inline unsigned long int index_for_config_43(Config_store config) ;
inline unsigned long int index_for_config_44(Config_store config) ;
inline unsigned long int index_for_config_45(Config_store config) ;
inline unsigned long int index_for_config_46(Config_store config) ;
inline unsigned long int index_for_config_47(Config_store config) ;
inline unsigned long int index_for_config_48(Config_store config) ;
inline unsigned long int index_for_config_49(Config_store config) ;

inline unsigned long int index_for_config_fast(Pattern pattern, Config_store config);

/* From a pattern and a config, compute a number that is the index
   of the config, generated by list_variations(pattern, -), that 
   is matched by the config.
   The config must be defined on set bits of the pattern.
*/
inline unsigned long int index_for_config(Pattern pattern, Config_store config) REGPARM(2);


#endif

